version: '3.8'

services:
frontend:
build: ./frontend
ports:
- "3000:3000"
depends_on:
- backend

backend:
build: ./backend
ports:
- "1337:1337"
environment:
APP_KEYS: myKeyA,myKeyB
NODE_ENV: development